# Generated by Django 4.2.2 on 2023-06-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_name', models.CharField(default='', max_length=60, primary_key=True, serialize=False)),
            ],
        ),
    ]
