# Generated by Django 4.2.3 on 2023-07-25 23:36

import cap_feed.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('sent', models.DateTimeField()),
                ('status', models.CharField(choices=[('Actual', 'Actual'), ('Exercise', 'Exercise'), ('System', 'System'), ('Test', 'Test'), ('Draft', 'Draft')])),
                ('msg_type', models.CharField(choices=[('Alert', 'Alert'), ('Update', 'Update'), ('Cancel', 'Cancel'), ('Ack', 'Ack'), ('Error', 'Error')])),
                ('source', models.CharField(blank=True, default='', max_length=255)),
                ('scope', models.CharField(choices=[('Public', 'Public'), ('Restricted', 'Restricted'), ('Private', 'Private')])),
                ('restriction', models.CharField(blank=True, default='', max_length=255)),
                ('addresses', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.TextField(blank=True, default='')),
                ('references', models.TextField(blank=True, default='')),
                ('incidents', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='en-US', max_length=255)),
                ('category', models.CharField(choices=[('Geo', 'Geo'), ('Met', 'Met'), ('Safety', 'Safety'), ('Security', 'Security'), ('Rescue', 'Rescue'), ('Fire', 'Fire'), ('Health', 'Health'), ('Env', 'Env'), ('Transport', 'Transport'), ('Infra', 'Infra'), ('CBRNE', 'CBRNE'), ('Other', 'Other')])),
                ('event', models.CharField(max_length=255)),
                ('response_type', models.CharField(blank=True, choices=[('Shelter', 'Shelter'), ('Evacuate', 'Evacuate'), ('Prepare', 'Prepare'), ('Execute', 'Execute'), ('Avoid', 'Avoid'), ('Monitor', 'Monitor'), ('Assess', 'Assess'), ('AllClear', 'AllClear'), ('None', 'None')], default='')),
                ('urgency', models.CharField(choices=[('Immediate', 'Immediate'), ('Expected', 'Expected'), ('Future', 'Future'), ('Past', 'Past'), ('Unknown', 'Unknown')])),
                ('severity', models.CharField(choices=[('Extreme', 'Extreme'), ('Severe', 'Severe'), ('Moderate', 'Moderate'), ('Minor', 'Minor'), ('Unknown', 'Unknown')])),
                ('certainty', models.CharField(choices=[('Observed', 'Observed'), ('Likely', 'Likely'), ('Possible', 'Possible'), ('Unlikely', 'Unlikely'), ('Unknown', 'Unknown')])),
                ('audience', models.CharField(blank=True, default='')),
                ('event_code', models.CharField(blank=True, default='', max_length=255)),
                ('effective', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('onset', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, default=cap_feed.models.AlertInfo.default_expire)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('headline', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('instruction', models.TextField(blank=True, default=None, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, default='', max_length=255)),
                ('parameter', models.CharField(blank=True, default='', max_length=255)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='cap_feed.alert')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_desc', models.TextField()),
                ('altitude', models.CharField(blank=True, default='')),
                ('ceiling', models.CharField(blank=True, default='')),
                ('alert_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('iso3', models.CharField(unique=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('polygon', models.TextField(blank=True, default='')),
                ('multipolygon', models.TextField(blank=True, default='')),
                ('centroid', models.CharField(blank=True, default='', max_length=255)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.continent')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.TextField(blank=True, default='')),
                ('centroid', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('meteoalarm', 'meteoalarm'), ('aws', 'aws'), ('nws_us', 'nws_us'), ('meteo_ru', 'meteo_ru')])),
                ('polling_interval', models.IntegerField(choices=[(10, '10 seconds'), (20, '20 seconds'), (30, '30 seconds'), (40, '40 seconds'), (50, '50 seconds'), (60, '60 seconds'), (70, '70 seconds'), (80, '80 seconds'), (90, '90 seconds'), (100, '100 seconds'), (110, '110 seconds'), (120, '120 seconds')])),
                ('atom', models.CharField(default='http://www.w3.org/2005/Atom', editable=False)),
                ('cap', models.CharField(default='urn:oasis:names:tc:emergency:cap:1.2', editable=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.region'),
        ),
        migrations.CreateModel(
            name='AlertInfoParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('alert_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoAreaPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('alert_info_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoAreaGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('alert_info_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea')),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoAreaCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('alert_info_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country'),
        ),
        migrations.AddField(
            model_name='alert',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.feed'),
        ),
    ]
