# Generated by Django 4.2.2 on 2023-06-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cap_feed.region'),
        ),
    ]
