# Generated by Django 4.2.3 on 2023-07-26 09:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception', models.CharField(default='exception', max_length=255)),
                ('error_message', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('response', models.TextField(default='')),
                ('alert_id', models.CharField(blank=True, default='', max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.feed')),
            ],
        ),
        migrations.AddConstraint(
            model_name='feedlog',
            constraint=models.UniqueConstraint(fields=('alert_id', 'description'), name='unique_alert_error'),
        ),
    ]
