# Generated by Django 4.2.3 on 2023-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
