# Generated by Django 4.2.2 on 2023-06-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0002_alert_polygon_alter_alert_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='event',
            field=models.CharField(max_length=255),
        ),
    ]
