# Generated by Django 4.2.2 on 2023-06-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0002_country_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='cap_feed.country'),
        ),
    ]
