# Generated by Django 4.2.3 on 2023-08-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0002_feed_enable_polling_feed_enable_rebroadcast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='enable_polling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('testing', 'testing'), ('unusable', 'unusable'), ('active', 'active'), ('inactive', 'inactive')], default='active'),
        ),
    ]
