# Generated by Django 4.2.2 on 2023-06-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0003_alert_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='cap_feed.country'),
        ),
    ]
