# Generated by Django 4.2.3 on 2023-07-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0003_feedlog_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('polygon', models.TextField(blank=True, default='')),
                ('multipolygon', models.TextField(blank=True, default='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country')),
            ],
        ),
    ]
