# Generated by Django 4.2.3 on 2023-08-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0003_alter_feed_enable_polling_alter_feed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('testing', 'testing'), ('inactive', 'inactive'), ('unusable', 'unusable')], default='active'),
        ),
    ]
