# Generated by Django 4.2.3 on 2023-08-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0004_alter_feed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='cap_feed.alert'),
        ),
    ]
