# Generated by Django 4.2.3 on 2023-07-31 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0004_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alert')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.district')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='districts',
            field=models.ManyToManyField(through='cap_feed.AlertDistrict', to='cap_feed.district'),
        ),
    ]
