# Generated by Django 4.2.3 on 2023-07-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0005_alertdistrict_alert_districts'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='max_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='max_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='min_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='min_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
