# Generated by Django 4.2.3 on 2023-08-18 00:01

import cap_feed.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0005_alter_alertinfo_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('expires', models.DateTimeField(default=cap_feed.models.ExpiredAlert.default_expire)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.feed')),
            ],
        ),
    ]
