# Generated by Django 4.2.2 on 2023-06-28 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0006_alert_effective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='centroid',
        ),
        migrations.RemoveField(
            model_name='country',
            name='iso',
        ),
        migrations.AddField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.SET_DEFAULT, to='cap_feed.continent'),
        ),
    ]
