# Generated by Django 4.2.2 on 2023-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0006_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='polling_rate',
            field=models.IntegerField(choices=[(30, '00:30'), (45, '00:45'), (60, '01:00'), (75, '01:15'), (90, '01:30'), (105, '01:45'), (120, '02:00')]),
        ),
    ]
