# Generated by Django 4.2.3 on 2023-08-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0006_district_max_latitude_district_max_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='max_latitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='max_longitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='min_latitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='min_longitude',
            field=models.FloatField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='multipolygon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
