# Generated by Django 4.2.2 on 2023-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0007_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='polling_interval',
            field=models.IntegerField(choices=[(30, '30 seconds'), (45, '45 seconds'), (60, '60 seconds'), (75, '75 seconds'), (90, '90 seconds'), (105, '105 seconds'), (120, '120 seconds')]),
        ),
    ]
