# Generated by Django 4.2.3 on 2023-08-26 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0007_alter_admin1_name_alter_alert_code_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpiredAlert',
            new_name='ProcessedAlert',
        ),
    ]
