# Generated by Django 4.2.3 on 2023-08-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0007_alter_district_max_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='polling_interval',
            field=models.IntegerField(choices=[(10, '10 seconds'), (15, '15 seconds'), (20, '20 seconds'), (25, '25 seconds'), (30, '30 seconds'), (35, '35 seconds'), (40, '40 seconds'), (45, '45 seconds'), (50, '50 seconds'), (55, '55 seconds')]),
        ),
    ]
