# Generated by Django 4.2.2 on 2023-06-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0009_continent_remove_country_centroid_remove_country_iso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='polygon',
        ),
        migrations.RemoveField(
            model_name='source',
            name='verification_keys',
        ),
        migrations.AddField(
            model_name='country',
            name='multipolygon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='country',
            name='polygon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='source',
            name='iso3',
            field=models.CharField(max_length=3),
        ),
    ]
