# Generated by Django 4.2.3 on 2023-08-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0009_remove_feed_abbreviation_alter_feed_polling_interval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('testing', 'testing'), ('unusable', 'unusable'), ('unused', 'unused'), ('operating', 'operating')], default='operating'),
        ),
    ]
