# Generated by Django 4.2.3 on 2023-08-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0010_alter_feed_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='official',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feed',
            name='status',
            field=models.CharField(choices=[('unused', 'unused'), ('testing', 'testing'), ('unusable', 'unusable'), ('operating', 'operating')], default='operating'),
        ),
    ]
