# Generated by Django 4.2.3 on 2023-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0010_alter_alert_addresses_alter_alert_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfoarea',
            name='altitude',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alertinfoarea',
            name='ceiling',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
