# Generated by Django 4.2.2 on 2023-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0010_remove_alert_polygon_remove_source_verification_keys_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='format',
            field=models.CharField(choices=[('meteoalarm', 'meteoalarm'), ('capfeedphp', 'capfeedphp')]),
        ),
        migrations.AlterField(
            model_name='source',
            name='iso3',
            field=models.CharField(choices=[]),
        ),
        migrations.AlterField(
            model_name='source',
            name='polling_interval',
            field=models.IntegerField(choices=[(10, '10 seconds'), (20, '20 seconds'), (30, '30 seconds'), (40, '40 seconds'), (50, '50 seconds'), (60, '60 seconds'), (70, '70 seconds'), (80, '80 seconds'), (90, '90 seconds'), (100, '100 seconds'), (110, '110 seconds'), (120, '120 seconds')]),
        ),
    ]
