# Generated by Django 4.2.2 on 2023-07-03 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0011_alter_continent_id_alter_country_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='senderName',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap_feed.source'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='centroid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='cap_feed.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(default='-1', on_delete=django.db.models.deletion.CASCADE, to='cap_feed.region'),
        ),
    ]
