# Generated by Django 4.2.2 on 2023-07-05 11:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0012_alert_description_alert_sendername_alert_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='country',
        ),
        migrations.RemoveField(
            model_name='source',
            name='iso3',
        ),
        migrations.AlterField(
            model_name='continent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso3',
            field=models.CharField(unique=True, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
