# Generated by Django 4.2.2 on 2023-07-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0013_remove_alert_country_remove_source_iso3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cap_feed.country'),
            preserve_default=False,
        ),
    ]
