# Generated by Django 4.2.3 on 2023-07-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0017_alter_alert_addresses_alter_alert_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertInfoAreaCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoAreaGeocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlertInfoAreaPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='areageocode',
            name='info_area',
        ),
        migrations.RemoveField(
            model_name='areapolygon',
            name='info_area',
        ),
        migrations.RenameModel(
            old_name='InfoArea',
            new_name='AlertInfoArea',
        ),
        migrations.DeleteModel(
            name='AreaCircle',
        ),
        migrations.DeleteModel(
            name='AreaGeocode',
        ),
        migrations.DeleteModel(
            name='AreaPolygon',
        ),
        migrations.AddField(
            model_name='alertinfoareapolygon',
            name='alert_info_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea'),
        ),
        migrations.AddField(
            model_name='alertinfoareageocode',
            name='alert_info_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea'),
        ),
        migrations.AddField(
            model_name='alertinfoareacircle',
            name='alert_info_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfoarea'),
        ),
    ]
