# Generated by Django 4.2.3 on 2023-07-12 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0018_alertinfoareacircle_alertinfoareageocode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertinfo',
            name='parameter',
        ),
        migrations.CreateModel(
            name='AlertInfoParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('alert_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cap_feed.alertinfo')),
            ],
        ),
    ]
