# Generated by Django 4.2.3 on 2023-07-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0019_remove_alertinfo_parameter_alertinfoparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfoparameter',
            name='value',
            field=models.TextField(),
        ),
    ]
