# Generated by Django 4.2.3 on 2023-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0020_alter_alertinfoparameter_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertinfo',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='instruction',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
