# Generated by Django 4.2.3 on 2023-07-15 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0021_alter_alertinfo_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertinfo',
            name='parameter',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alertinfo',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='cap_feed.alert'),
        ),
    ]
