# Generated by Django 4.2.3 on 2023-07-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap_feed', '0022_alertinfo_parameter_alter_alertinfo_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default='hi', max_length=255),
            preserve_default=False,
        ),
    ]
